/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CuradoriaRouteImport } from './routes/curadoria'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as CategoriasCategoriaRouteImport } from './routes/categorias.$categoria'
import { Route as ConversasIndexRouteImport } from './routes/conversas.index'
import { Route as ConversasIdRouteImport } from './routes/conversas.$id'
import { Route as FaqsIdRouteImport } from './routes/faqs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CuradoriaRoute = CuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasCategoriaRoute = CategoriasCategoriaRouteImport.update({
  id: '/categorias/$categoria',
  path: '/categorias/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIndexRoute = ConversasIndexRouteImport.update({
  id: '/conversas/',
  path: '/conversas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasIdRoute = ConversasIdRouteImport.update({
  id: '/conversas/$id',
  path: '/conversas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIdRoute = FaqsIdRouteImport.update({
  id: '/faqs/$id',
  path: '/faqs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curadoria': typeof CuradoriaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/faqs/$id': typeof FaqsIdRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/conversas/': typeof ConversasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curadoria': typeof CuradoriaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/faqs/$id': typeof FaqsIdRoute
  '/categorias': typeof CategoriasIndexRoute
  '/conversas': typeof ConversasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/curadoria': typeof CuradoriaRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/usuarios': typeof UsuariosRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/conversas/$id': typeof ConversasIdRoute
  '/faqs/$id': typeof FaqsIdRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/conversas/': typeof ConversasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/curadoria'
    | '/importar'
    | '/login'
    | '/notificacoes'
    | '/usuarios'
    | '/categorias/$categoria'
    | '/conversas/$id'
    | '/faqs/$id'
    | '/categorias/'
    | '/conversas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/curadoria'
    | '/importar'
    | '/login'
    | '/notificacoes'
    | '/usuarios'
    | '/categorias/$categoria'
    | '/conversas/$id'
    | '/faqs/$id'
    | '/categorias'
    | '/conversas'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/configuracoes'
    | '/curadoria'
    | '/importar'
    | '/login'
    | '/notificacoes'
    | '/usuarios'
    | '/categorias/$categoria'
    | '/conversas/$id'
    | '/faqs/$id'
    | '/categorias/'
    | '/conversas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CuradoriaRoute: typeof CuradoriaRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  UsuariosRoute: typeof UsuariosRoute
  CategoriasCategoriaRoute: typeof CategoriasCategoriaRoute
  ConversasIdRoute: typeof ConversasIdRoute
  FaqsIdRoute: typeof FaqsIdRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ConversasIndexRoute: typeof ConversasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curadoria': {
      id: '/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof CuradoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$categoria': {
      id: '/categorias/$categoria'
      path: '/categorias/$categoria'
      fullPath: '/categorias/$categoria'
      preLoaderRoute: typeof CategoriasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/': {
      id: '/conversas/'
      path: '/conversas'
      fullPath: '/conversas/'
      preLoaderRoute: typeof ConversasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas/$id': {
      id: '/conversas/$id'
      path: '/conversas/$id'
      fullPath: '/conversas/$id'
      preLoaderRoute: typeof ConversasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/$id': {
      id: '/faqs/$id'
      path: '/faqs/$id'
      fullPath: '/faqs/$id'
      preLoaderRoute: typeof FaqsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CuradoriaRoute: CuradoriaRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  UsuariosRoute: UsuariosRoute,
  CategoriasCategoriaRoute: CategoriasCategoriaRoute,
  ConversasIdRoute: ConversasIdRoute,
  FaqsIdRoute: FaqsIdRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ConversasIndexRoute: ConversasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
